#!/usr/bin/env bash
# script description: array of topics
# build Stage: Alpha
# Author: tiago medice (@a73s)

topics=(
"TP_MESITER_COMPANY"
"TP_AGGIORNAMENTO_COMPANY"
"TP_MANAGER_COMPANY"
"TP_MESITER_FAULT"
"TP_MANAGER_FAULT"
"TP_AGGIORNAMENTO_DRIVEN"
"TP_MANAGER_DRIVEN"
)