#!/usr/bin/env bash
# script description: array of topics
# build Stage: Alpha
# Author: tiago medice (@a73s)

topics=(
"TP_ELABORA_AZIENDA"
"TP_AGGIORNAMENTO_AZIENDA"
"TP_CENSIMENTO_AZIENDA"
"TP_ELABORA_DENUNCIA"
"TP_CENSIMENTO_DENUNCIA"
"TP_AGGIORNAMENTO_ISCRITTO"
"TP_CENSIMENTO_ISCRITTO"
)